// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9vR-ocoxanxXxg_2UTzTWpZy3uSESQY',
    appId: '1:669890937218:web:5b8981e3d673117dd8cf9b',
    messagingSenderId: '669890937218',
    projectId: 'portfolio-67419',
    authDomain: 'portfolio-67419.firebaseapp.com',
    storageBucket: 'portfolio-67419.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW9liFKfGwwV6NVJoDn8BWG3W2875577Y',
    appId: '1:669890937218:android:b85660a6801f5f00d8cf9b',
    messagingSenderId: '669890937218',
    projectId: 'portfolio-67419',
    storageBucket: 'portfolio-67419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkctXHx65wFKN31nTYsHozcOPO6Tgh9MI',
    appId: '1:669890937218:ios:ed458e981cab65d0d8cf9b',
    messagingSenderId: '669890937218',
    projectId: 'portfolio-67419',
    storageBucket: 'portfolio-67419.firebasestorage.app',
    androidClientId: '669890937218-1q58va63sfb5gajsodi6kk70m7evtr16.apps.googleusercontent.com',
    iosClientId: '669890937218-la5ni1s24rm9ivq4qc6aar3tdaqal527.apps.googleusercontent.com',
    iosBundleId: 'com.example.capitalMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkctXHx65wFKN31nTYsHozcOPO6Tgh9MI',
    appId: '1:669890937218:ios:ed458e981cab65d0d8cf9b',
    messagingSenderId: '669890937218',
    projectId: 'portfolio-67419',
    storageBucket: 'portfolio-67419.firebasestorage.app',
    androidClientId: '669890937218-1q58va63sfb5gajsodi6kk70m7evtr16.apps.googleusercontent.com',
    iosClientId: '669890937218-la5ni1s24rm9ivq4qc6aar3tdaqal527.apps.googleusercontent.com',
    iosBundleId: 'com.example.capitalMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf9vR-ocoxanxXxg_2UTzTWpZy3uSESQY',
    appId: '1:669890937218:web:2b9f13954634f9ccd8cf9b',
    messagingSenderId: '669890937218',
    projectId: 'portfolio-67419',
    authDomain: 'portfolio-67419.firebaseapp.com',
    storageBucket: 'portfolio-67419.firebasestorage.app',
  );

}